### ISSUE TITLE
DB/ api env processing / ADD createPool

### ISSUE THREAD

**Issue by amamj05** [InsideOutXminDay/minday#118]
- api 관련 코드 전부 환경변수 처리 했습니다  수정 안된 부분 있으면 아래 링크의 pr에 코멘트 부탁드릴게요!

- db.js 에 createPool 코드 추가 했습니다 pool 로 변경하실 때 사용해주세요!
(모든 코드가 바뀐게 아닌만큼 const mydb 를 지우진 말아주세요!)

_Originally posted by @amamj05 in https://github.com/InsideOutXminDay/minday/issues/116#issuecomment-2232662154_

**Comment by Hye1JEong** [comment]
확인했습니다!
